# Generated by Django 5.1.3 on 2024-11-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0002_alter_image_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images_1', to='Sport_News.news'),
        ),
    ]
