# Generated by Django 5.1.3 on 2024-11-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0005_media_dislike_count_photogallery_dislike_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike_count', models.IntegerField(blank=True, default=0, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reply_answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PF', 'Published'), ('PN', 'Pending')], default='DF', max_length=3)),
                ('replay_type', models.CharField(choices=[('Q', 'Question'), ('R', 'Response')], default='Q', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('avatar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.avatar')),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.comment')),
            ],
        ),
    ]
