# Generated by Django 5.1.3 on 2024-11-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0007_alter_replyanswer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyanswer',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.news'),
        ),
    ]
