# Generated by Django 5.1.3 on 2024-11-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0011_alter_news_createdusers_alter_news_updatedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='admin_approve',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_approve', to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.news'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replay_type',
            field=models.CharField(blank=True, choices=[('Q', 'Question'), ('R', 'Response')], default='Q', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('DF', 'Draft'), ('PF', 'Published'), ('PN', 'Pending')], default='DF', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='images_news', to='Sport_News.image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(blank=True, choices=[('IR', 'IRAN_NEWS'), ('WO', 'WORLD_NEWS')], default='IR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='Sport_News.tag'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.comment'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='createdUsers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts_0', to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='updatedUsers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts_1', to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='replyanswer',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.comment'),
        ),
        migrations.AlterField(
            model_name='replyanswer',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.news'),
        ),
        migrations.AlterField(
            model_name='replyanswer',
            name='replay_type',
            field=models.CharField(blank=True, choices=[('Q', 'Question'), ('R', 'Response')], default='Q', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('MANAGER', 'MANAGER'), ('USER', 'USER')], default='USER', max_length=200),
        ),
    ]
