# Generated by Django 5.1.3 on 2024-11-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0012_role_created_date_role_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.comment'),
        ),
        migrations.AlterField(
            model_name='media',
            name='createdUsers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_0', to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('IR', 'Iran_Media'), ('WO', 'World_Media')], default='IR', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='poster_file_name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('DF', 'Draft'), ('PF', 'Published'), ('PN', 'Pending')], default='DF', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_1', to='Sport_News.tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='updatedUsers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_1', to='Sport_News.user'),
        ),
    ]
