# Generated by Django 5.1.3 on 2024-11-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0013_alter_media_comment_alter_media_createdusers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.comment'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.news'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_2', to='Sport_News.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='createdUsers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_2', to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='images_tag', to='Sport_News.image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(blank=True, choices=[('DF', 'Draft'), ('PF', 'Published'), ('PN', 'Pending')], default='DF', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updatedUsers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_3', to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='visibility',
            field=models.CharField(blank=True, choices=[('VI', 'Visible'), ('IN', 'Invisible')], default='IN', max_length=2, null=True),
        ),
    ]
