# Generated by Django 5.1.3 on 2024-11-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0014_alter_photogallery_comment_alter_photogallery_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreporting',
            name='admin_reason_type',
            field=models.CharField(blank=True, choices=[('TR', 'True'), ('FS', 'False')], default='TR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='errorreporting',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.news'),
        ),
        migrations.AlterField(
            model_name='errorreporting',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('CP', 'Content Problem'), ('WP', 'Writing Problem'), ('OCP', 'Other Problem')], default='OCP', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='errorreporting',
            name='users',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_1', to='Sport_News.news'),
        ),
        migrations.AlterField(
            model_name='replyanswer',
            name='status',
            field=models.CharField(blank=True, choices=[('DF', 'Draft'), ('PF', 'Published'), ('PN', 'Pending')], default='DF', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reporting_a_violation',
            name='admin_reason_type',
            field=models.CharField(blank=True, choices=[('TR', 'True'), ('FS', 'False')], default='TR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reporting_a_violation',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comments', to='Sport_News.comment'),
        ),
        migrations.AlterField(
            model_name='reporting_a_violation',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='reporting_a_violation',
            name='violation_type',
            field=models.CharField(blank=True, choices=[('IN', 'Insult'), ('PO', 'Political'), ('SP', 'Spam'), ('VW', 'Vulgar Words')], default='IN', max_length=3, null=True),
        ),
    ]
