# Generated by Django 5.1.3 on 2024-11-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0015_alter_errorreporting_admin_reason_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='description',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='metacontactus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.metacontactus'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='related_unit',
            field=models.CharField(blank=True, choices=[('NE', 'News'), ('MS', 'Management Site'), ('VD', 'Video'), ('TE', 'Technical'), ('AD', 'Advertising'), ('MA', 'Marketing')], default='NE', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.user'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='image_of_newspaper',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
