# Generated by Django 5.1.3 on 2024-11-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0017_alter_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='Category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport_News.category'),
        ),
    ]
