# Generated by Django 5.1.3 on 2024-11-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0018_podcast_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
