# Generated by Django 5.1.3 on 2024-12-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0020_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Sliders'),
        ),
    ]
