# Generated by Django 5.1.3 on 2024-12-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0021_image_file_photogallery_file_alter_slider_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='images_news', to='Sport_News.image'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='Sport_News.tag'),
        ),
    ]
