# Generated by Django 5.1.3 on 2024-12-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0022_news_image_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
    ]
