# Generated by Django 5.1.3 on 2024-12-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0023_news_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='file',
        ),
        migrations.AlterField(
            model_name='news',
            name='main_picture',
            field=models.FileField(blank=True, null=True, upload_to='news/'),
        ),
    ]
