# Generated by Django 5.1.3 on 2024-12-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport_News', '0024_remove_news_file_alter_news_main_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Sport_News.category'),
        ),
    ]
